// The honesty ledger, read from the trace rather than written here.
//
// A project that states its limits precisely makes a stronger claim than one that does not mention
// them. This table is generated by the C++ tool from the run itself, so it cannot drift into
// flattery: if a number was not measured, the file says so and this panel repeats it.

import type { Limit, LimitStatus, Trace } from "../model/trace";

const TAG: Record<LimitStatus, string> = {
  measured: "tag tag--good",
  "not-measurable": "tag tag--bad",
  simulated: "tag tag--recovery",
};

interface Props {
  readonly trace: Trace;
}

export function Ledger({ trace }: Props) {
  return (
    <section className="panel ledger">
      <h2>What this run measured, and what it cannot</h2>
      <p className="why">
        Generated by <code>tools/trace</code> from the run, not written by hand.
      </p>
      <table>
        <tbody>
          {trace.header.limits.map((limit: Limit) => (
            <tr key={limit.claim}>
              <td>{limit.claim}</td>
              <td style={{ whiteSpace: "nowrap" }}>
                <span className={TAG[limit.status]}>{limit.status}</span>
              </td>
              <td style={{ color: "var(--ink-soft)", fontSize: 13 }}>{limit.note}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}
